"""Train a TimeSeriesCNN to predict force from sensor response.

Imports the simulation data exported by ``export_forward_simulation_data.py``
(or regenerated by the ``forward_simulation_*.ipynb`` notebooks), defines the
CNN from ``neural_networks.py``, and trains it with a plain Adam loop via
jaxopt's ``OptaxSolver``.

Usage:
    python scripts/train_neural_network.py --structure input_source_2
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

import jax
import jax.numpy as jnp
import numpy as np
import optax
from jaxopt import OptaxSolver

from neural_networks import TimeSeriesCNN, minmax_scaler

STRUCTURES = ["input_source_2", "input_source_4", "input_source_8", "circular_structure"]


def load_dataset(data_dir: Path, structure: str):
    data = np.load(data_dir / f"forward_sim_{structure}.npz")
    return jnp.asarray(data["input_data"]), jnp.asarray(data["output_data"])


def split_dataset(input_data: jnp.ndarray, output_data: jnp.ndarray, seed: int = 0, test_frac: float = 0.2):
    key = jax.random.PRNGKey(seed)
    n = input_data.shape[0]
    test_n = max(1, int(round(n * test_frac)))
    test_idx = jax.random.choice(key, n, shape=(test_n,), replace=False)
    mask = jnp.ones(n, dtype=bool).at[test_idx].set(False)
    return input_data[mask], output_data[mask], input_data[test_idx], output_data[test_idx]


def train(structure: str, data_dir: Path, iters: int, lr: float, seed: int = 0):
    input_data, output_data = load_dataset(data_dir, structure)
    train_x, train_y, test_x, test_y = split_dataset(input_data, output_data, seed=seed)
    print(f"[{structure}] train samples: {train_x.shape[0]}, test samples: {test_x.shape[0]}")

    scaler = minmax_scaler(train_x, train_y)
    train_xn, train_yn = scaler.transform(train_x, train_y)
    test_xn, test_yn = scaler.transform(test_x, test_y)

    model = TimeSeriesCNN(output_features=output_data.shape[-1])
    key = jax.random.PRNGKey(seed)
    params = model.init(key, train_xn)

    def loss_fn(params, data):
        x, y = data
        pred = model.apply(params, x)
        return jnp.mean((pred - y) ** 2)

    solver = OptaxSolver(opt=optax.adam(lr), fun=loss_fn, maxiter=iters)
    state = solver.init_state(params, (train_xn, train_yn))

    print_every = max(1, iters // 10)
    for i in range(iters):
        params, state = solver.update(params, state, (train_xn, train_yn))
        if i % print_every == 0 or i == iters - 1:
            train_loss = loss_fn(params, (train_xn, train_yn))
            test_loss = loss_fn(params, (test_xn, test_yn))
            print(f"  iter {i:4d}  train loss {train_loss:.4e}  test loss {test_loss:.4e}")

    return params, scaler


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--structure", choices=STRUCTURES, required=True)
    parser.add_argument("--data-dir", type=Path, default=Path("data"))
    parser.add_argument("--iters", type=int, default=300, help="Number of Adam steps.")
    parser.add_argument("--lr", type=float, default=1e-2, help="Adam learning rate.")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    train(args.structure, args.data_dir, args.iters, args.lr, args.seed)


if __name__ == "__main__":
    main()
